# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Likelihood of offering specific response
#' 
#' This function returns the value of likelihood of a person with ability parameter \eqn{\theta} having offered the specific response profile stored in answers conditional on the item-level parameters. 
#' 
#' @param cat_df An object of \code{Cat} class
#' @param t A numeric for possible value of theta (position on the latent scale of interest)
#' @param items A vector containing the index of the question items we want to include in the likelihood calculations
#' 
#' @return A value of the likelihood of each respondent offering spcific response
#' 
#' @details Letting \eqn{q_i(\theta_j)=1-p_i(\theta_j)}, the likelihood function associated with the responses profile \eqn{y_j} is..
#' \deqn{L(\theta_j|\mathbf{y}_{j})=\prod^{j}_{i=1}p_i(\theta_j)^{y_{ij}}q_i(\theta_j)^{(1-y_{ij}}}, where \eqn{y_j} is evaluated based only on the questions the respondet has actually had opportunity to answer
#'  
#' @export
likelihood <- function(cat_df, t) {
    .Call('catSurv_likelihood', PACKAGE = 'catSurv', cat_df, t)
}

#' Probabilities of the responses to a question given theta 
#' 
#' This function calculates the probabilities of a specific set of responses to a specific question for a specific value of \eqn{\theta}.
#' 
#' @param cat_df An object of \code{Cat} class
#' @param t A double indicating the potential value for \eqn{\theta_j}
#' @param q An integer indicating the index of the question
#' @param ret_prob (For polytonomous implementation only) A double-vector where the calculations carried out by this function will be stored.
#' 
#' @return A vector consisting of the probability of a correct response for each respondent on item \eqn{i}.
#' 
#' @details The probability of a correct response for respondent \eqn{j} on item \eqn{i} is ....
#' where \eqn{\theta_j} is respondent \eqn{j_i}'s position on the latent scle of interest, \eqn{a_i} is item \eqn{i}'s discrimination parameter,
#'  \eqn{b_i} is item i's difficulty parameter, and \eqn{c_i} is item \eqn{i}'s guessing parameter.
#'  
#' @export
probability <- function(cat_df, t, q) {
    .Call('catSurv_probability', PACKAGE = 'catSurv', cat_df, t, q)
}

