# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

<<<<<<< HEAD
#' Probabilities of the responses to a question given theta 
#' 
#' This function calculates the probabilities of a specific set of responses to a specific question for a specific value of \eqn{\theta}.
#' 
#' @param cat_df An object of \code{Cat} class
#' @param t A double indicating the potential value for \eqn{\theta_j}
#' @param q An integer indicating the index of the question
#' @param ret_prob (For polytonomous implementation only) A double-vector where the calculations carried out by this function will be stored.
#' 
#' @return A vector consisting of the probability of a correct response for each respondent on item \eqn{i}.
#' 
#' @details The probability of a correct response for respondent \eqn{j} on item \eqn{i} is ....
#' where \eqn{\theta_j} is respondent \eqn{j_i}'s position on the latent scle of interest, \eqn{a_i} is item \eqn{i}'s discrimination parameter,
#'  \eqn{b_i} is item i's difficulty parameter, and \eqn{c_i} is item \eqn{i}'s guessing parameter.
#'  
=======
#' Find the weighted mean of several normal distributions
#' 
#' @param x A vector of values where the weighted normal is being evaluated
#' @param means The means of the vaious normal distributions
#' @param weights The weight assigned to each normal distribution
#' @param sd A single number for the common standard deviation
>>>>>>> origin/GroupBranch
#' @export
probability <- function(cat_df, t, q) {
    .Call('catSurv_probability', PACKAGE = 'catSurv', cat_df, t, q)
}

